version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    environment:
      DOCKER_USERNAME: $DOCKER_USERNAME
      DOCKER_PASSWORD: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t comm/alist-mod:latest .
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run:
          name: Push Docker Image
          command: docker push comm/alist-mod:latest
workflows:
  build-and-push:
    jobs:
      - build